# Generated by Django 2.2.10 on 2020-08-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_payment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
