# Generated by Django 2.2.10 on 2020-05-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_photo', models.ImageField(default='emp_avtar.jpg', upload_to='emplyees_photo')),
                ('owner_address', models.TextField(max_length=200)),
                ('owner_mobile', models.CharField(max_length=10)),
                ('owner_email', models.EmailField(default='xyz@gmail.com', max_length=254)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=8)),
                ('owner_work_start', models.DateTimeField(auto_now=True)),
                ('owner_action', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.TextField(default='optional')),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_owner.House_Owner')),
            ],
        ),
    ]
