# Generated by Django 2.2.10 on 2020-05-24 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_pay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
