# Generated by Django 2.2.10 on 2020-08-01 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_owner', '0002_auto_20200524_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_owner',
            name='owner_work_end',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='house_owner',
            name='owner_work_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
